# Generated by Django 3.0.7 on 2020-11-23 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='null@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='lastLoggedIn',
            field=models.DateField(default=datetime.date(2020, 11, 23)),
        ),
        migrations.AddField(
            model_name='users',
            name='phoneNum',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='pwd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
