# Generated by Django 3.1.3 on 2020-12-15 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201123_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastLoggedIn',
            field=models.DateField(default=datetime.date(2020, 12, 15)),
        ),
    ]
