# Generated by Django 3.1.3 on 2020-12-31 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20201215_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastLoggedIn',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
    ]
